apiVersion: v1
kind: Secret
metadata:
    name: gmail-smtp-secret
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Qgq45lj4vsmy0Gce7yOxrPpLfj9xpseBDOCF,iv:EqnT3E+REptmjFx6lWdYVInOrBLwdHiNamUpbDzCAZg=,tag:INE8WFBIJrwe/ucNm/SWqA==,type:str]
    password: ENC[AES256_GCM,data:gWEIHxDmP7ugihe1/VWxwg==,iv:zjRQ7xYOEy///Ku7V+ASa+EY3MmZUB9Qp1tD4yEdgbg=,tag:uDHmY6WoNy8FAUgzn4GZew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQTZCQ0ZCZWZBZnliaktm
            OHpOTnI1NjZhazdDaitkU0tVTnp6cEVQeUV3Cmpadm5UVHBOZ3lKQU0vK0ZReDBQ
            RVAvZE11OEVNclNWSGRDRU5jdW8vTmsKLS0tIGRmYmJHMXR2WGsyUW9UVDRSSDhQ
            dTZYNStvbFhZdDh4amRKdUtUOUdUTWcK9QUKF/p4uYlyGHYWVK373ihLiBzh89dL
            Rkhz6+MtNmmjOVJMRf66In29X/c4MXJIrlNTzlsyjQdpxZ0hGmeXAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jcjvjd8vg2pkyjtv2y49ccgrzxy9uf9n5e2wx3d627ufd3705uysryuuxk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T09:56:49Z"
    mac: ENC[AES256_GCM,data:rOWmQh9+s4m8bNO5E+kaIlv4NpT78YQPaRBLhvkceJppPUThlK+qpyvJLgfx8Jw8W6tBR9igbvoVy4vzqaWsR5zwQ3Ab6LsphHb1+4DbPNnUQ252Uqh9UyunIzvx+LBGK131aHqYJtO6ibHIzDPCOIkOslcWXuXcVosLEQUF2V0=,iv:EihWbxb60/o5bhD6vhmlb9lZR5mvdKaeWrcpP9FbaoI=,tag:INckIUeTneU6BFaN+Wa9dA==,type:str]
    version: 3.13.3
