apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RDAJDcxgSVjB3ZnaLG1SfGhc+7lixpf6kEQWYpcZ81bkbuGkQuesAwbMmL6tAZDJTC6pBfyD1QFjCjlIM0WTMpyPGXt3vCgtK0t8xLDGDNAPyUY6kfBIIlHRm1DoGDmzQNyUD59GS9AJp2xGmW9ZxCX9LaMCjBqRlGJZi/ilzk6mkS6UTL+c4L1/s2mtxZ0pM88UyQj2Zf60Bu2lfDAgFWDOZTejjkSTtwoU3Na4zb2E6Ue8GN7szFLRNt35AJVUG4cAbMIwUu6keofgvzO9wNbnsb6zC5CaDWybto80CDqCIz7AnzE5ak0mGNA=,iv:wJKmicj/bGi8HROlc1p5aWgtQ1ocprBMnWOEW/JAs0s=,tag:R6HJETiWkoewEj4zAU9kVg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN1V0NXFBYXZQQTZMYWhW
            UFc4KzBrQ0tGZlcwczFTQ25sSWtXK3crMWkwCjhkQ0NNQnRsQzN4VG5jcWJZckpE
            ZU1qRGNmWHBzMXA3VGpzbTltQ2NkWnMKLS0tIFAxaHpRMjhrb0VQZUJXeHRmWEhy
            d00wdjh5cDNVMit6Z1AycjRQM0FqdlEKZ+4KmnYc4RNraqsujAx8jZ7cFXcEcBrA
            PtXWesn+y++TLBHwSNuaCjwL2dsUaHnE5Q14A+aqKYR89pWPrRR5RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jcjvjd8vg2pkyjtv2y49ccgrzxy9uf9n5e2wx3d627ufd3705uysryuuxk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T13:58:00Z"
    mac: ENC[AES256_GCM,data:jUC0pxAQCy8H3+L8yq1rldjETeoPAOuyVTQNfomJ0m8mMFmgZwtCTlhCzkq2DF2nkvHyJfXQAlHv6ROMEJCPmm0jUAOALdn/EwjyDOy0nd7lKMRzEIsdDayDxHDaZKw8cf9bLYfXp9gpjuyh8uANXwK4PQn6hrtu51uQw1iu1PU=,iv:p87pmyWxiQGcjbs3ylaWugTOThCKUQ5I9DY5tjMS36Y=,tag:lrjGI0QLULn1xY42H1h0NQ==,type:str]
    version: 3.13.3
