apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:8PqaZTNjMCw=,iv:mCH0qUFakNUmaTEwdRGBeqcvsdVRI8en9uSlZIIwqoI=,tag:NhGM7l8esuwi2uFjlUPoow==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kZc0w79o2nL51htr,iv:bT3xXhSdGeMGGtKiwvuI1Hfre20c5ViZew4BBeyjJXw=,tag:naZX7O53GDWUGH71qgwIEA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-09-20T09:18:06Z"
    name: linkding-container-env
    namespace: linkding
    resourceVersion: "2873677"
    uid: 612404e6-595a-46a6-a02d-ad9890e6d82f
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMWJ2cmVzN0hnWldkVEI4
            eFM0aG5Ec045RU4vZVROWEszRE4yRW5GS2lVCnFBcDFZV2hndm9lUDkxam9yMUpP
            MUdVMVM4ZGlNOTlkV0ZjYW9yUVF2aVUKLS0tIGxjTUxNSy9VWEZtUUh3YmxiMVdJ
            SFI4cldIZ3NOMkYySTRCQnI3T1B2WTQKoMPvoq8SSeNUPVK2tRUTz2GcD49+DXnD
            VhIL4Nk2yUDrbN4oAGwIoHxqdeYBDzvoR/hWESvfkU1F/H5pmzbZ9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jcjvjd8vg2pkyjtv2y49ccgrzxy9uf9n5e2wx3d627ufd3705uysryuuxk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:25:03Z"
    mac: ENC[AES256_GCM,data:Dcb6Vegjop633Umro0TaCKnaayvRorIEiuNla7Zp60gfcF8Fq1Yb+VDSxFMPD7ikFfdfE0GaqaoP/Fo8mCkh+fw/fz8BCCEcSx0AlxL29kIVZC3O+F6wpIFZcq/cmVwvFTdq1TbvydgU1VnoOGyjzu2pTIRbbZBaE5q2lbm3qnU=,iv:giuAFnPXhW6D4BippptKxT7caUS8QSc2iymW46xpXU0=,tag:lj7QINUkpYahhjjofBz6zQ==,type:str]
    version: 3.13.3
