apiVersion: v1
kind: Secret
metadata:
    name: linkding-container-env
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:MrsJGxrR,iv:UazUdTJMXiOHqYhJNdTSGC4HB/azzjHfj5m92k5MM2s=,tag:j+lxa1M1z0Xh2huO7R3isA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:dt0MbZJnDQw=,iv:I9TBCbQDsDPITh9SbHpjM2abV8SYM1inXxVFjgw/mhI=,tag:1LFfmPJtQf//NZw9Woi0Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQkpmZ1hDeE9WcTRNb3Jj
            R3R3ck9ZVnRDMjNsaW5iSFdGbVJXTEI3bWxnCkMyT25pSW5Qa0dQMXYvM3JRS0ly
            ZXg2eEtpZjU4QmRCNGhqOW1sUnFjRmMKLS0tIEdTaTNFL1oyVkl3a1U4Kyt6dmlH
            c1Y1ZEVRSk9SOG5wY2t6WGFUa0QxeWMKkerIoGwlpfje0YZCKrIW7iVoywBgRZ6d
            5IuT8ezdvRmmoW31BwxvCYDRcVojSir1gaOQ3tPogSDdmvy3D0eaMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jcjvjd8vg2pkyjtv2y49ccgrzxy9uf9n5e2wx3d627ufd3705uysryuuxk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T07:29:28Z"
    mac: ENC[AES256_GCM,data:eosUPculh2v8GzZiyoFFHqILDdcgkSMNEnElM/7lukHg1fqM/84bam/I4kG3JqSgeEFqrefNhrqBPBlOBOuJqOoVuyfePSZdFoG/s5K9ka6B5qq4inWV6uX6+QBFNQCH/yV/JRwQrHEiDhiU9vfWKibbjiK2yXbHXoKogFNoikg=,iv:fpuCzOhJGgGSVu9g1ybdPeGg3kkBbFfTgv6guVz6P0Y=,tag:b4/RhTeOkT7lYjF4yEDHQA==,type:str]
    version: 3.13.3
