apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:KEkz5ojwsfk=,iv:AkUjWfTqW32orxlgLpI1sUvuTUJgp+tIHl2Z/rvAiZ4=,tag:yJLDFtxvOimXjTMem9iDxA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:4f6Ce4TSmpd1UIBJ,iv:xI9Y91joga18U0A8l5Zu4zCBgQHYCF4A5M+yE7JW1g0=,tag:R5sSAnCU6HN8k5V/Ge6Dpw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZjlKUVljNUd5eVd6dUVU
            OGNQVjhtMHgzUGltRGZMVVJwQU5TV2htSkhNCmt3UEpZR052eGEzYXZTZkcyZldO
            dmc0aERXR2RxZjNVSmd2RkFTVW05MGsKLS0tIDNxZXdXcmJlV3JZdkMrVDQ1TlhB
            SytHZ2xya3d6NFdZNTkrbGs4R1JpMmMKQ8Yp5DuM23qPZ7aDK+KjmYKOIr2qje7B
            KI/t2fYVgRsPiiR0o0hG+Doj0L8gJRYuEYQ7OIr292vLOczdJ2FV0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jcjvjd8vg2pkyjtv2y49ccgrzxy9uf9n5e2wx3d627ufd3705uysryuuxk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T17:12:35Z"
    mac: ENC[AES256_GCM,data:uoetop7h1egF79u2egoMORFMCMuhTIVXbuQuNqsKTGWKPxzJdUntBWQ6ckWnLrHwdNQ2/ZHCy7yc9dMaZL6wvl+A2O0JzlqpliEjvtoyC9UULjCnydstqdC3aUPHzyi8epGF8zbzotvJnXxY44SsDxX29jS0OFy/cdFY48ErsUY=,iv:/okPOujXvgmkcT4cP3pVej9m2YyGL9+FtFrwvLh6ieg=,tag:7lcveXb2COCILEgxuFkRDg==,type:str]
    version: 3.13.3
